### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by njh** [bbc/RadioVisDemo#2]
To make it easier to install dependencies

(whatever the equivalent is in Python for ```bundle install```)

**Comment by njh** [comment]
Added in 330a4d03620ddc06991b94e7ebce3f39585b775a

**Comment by njh** [comment]
See #13

**Comment by chrisn** [comment]
I tried `pip install --user -r requirements.txt` on Linux and got all kinds of errors. It'd be great if it worked there too, but installing wxPython via pip seems difficult ... https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html

**Comment by njh** [comment]
Oh, hm. It worked in Travis for me, which is Linux (Ubuntu 18 - Bionic Beaver). But it did take a very long time.

Is there any further work / improvements to do to `requirements.txt` or shall I close this issue?

**Comment by chrisn** [comment]
On Ubuntu 18, it's probably preferable to install using `sudo apt-get install -y python-wxgtk4.0` rather than through requirements.txt. I'll tweak the Travis config to see if we can get that to work.

**Comment by chrisn** [comment]
Resolved in the v2.0 release
